environment:
  matrix:
    - nodejs_version: "9"
    - nodejs_version: "8"
    - nodejs_version: "7"
    - nodejs_version: "6"
    - nodejs_version: "5"
    - nodejs_version: "4"

services:
  - mongodb

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - npm test
  - npm run lint
  - npm run nsp

build: off
