#!/bin/bash

#make sure firefox launches in the bottom right corner of the window

# read URLs from a data file in a loop
regex='([^[:space:]]+)[[:space:]]*(.*)'

func() {
    [[ $1 =~ $regex ]]
    url=${BASH_REMATCH[1]}
    name=${BASH_REMATCH[2]}

    # send URL to the firefox session
    firefox --width 1030 --height 768 $url &
    echo started firefox with $url

    # take a picture after waiting a bit for the load to finish
    sleep 4
    gm import -window root -crop 1004x768+414+228 -resize 500x350 $name.png
    echo grabbed screenshot $name.png
}

if [ $1 ]
then
  func "$1 $2"
else
    while read line
    do
        func $line
    done < urls
fi

