import { Schema, Document, Query, HydratedDocument } from 'mongoose';
import { expect } from 'tstyche';

interface IDocument extends Document {
  name?: string;
}

const schema: Schema<IDocument> = new Schema<IDocument>({ name: { type: 'String' } });

/* The following tests were generated by test/model.middleware.preposttypes.test.js (with GEN_TYPE_TEST hardcoded set to true) */

schema.pre('save', function() {
  expect(this).type.toBeAssignableTo<HydratedDocument<IDocument>>();
});

schema.post('save', function(res) {
  expect(this).type.toBeAssignableTo<HydratedDocument<IDocument>>();
  expect(res).type.not.toBeAssignableTo<Query<any, any>>();
});

schema.pre('save', { document: true, query: false }, function() {
  expect(this).type.toBeAssignableTo<HydratedDocument<IDocument>>();
});

schema.post('save', { document: true, query: false }, function(res) {
  expect(this).type.toBeAssignableTo<HydratedDocument<IDocument>>();
  expect(res).type.not.toBeAssignableTo<Query<any, any>>();
});

schema.pre('save', { document: true, query: true }, function() {
  expect(this).type.toBeAssignableTo<HydratedDocument<IDocument>>();
});

schema.post('save', { document: true, query: true }, function(res) {
  expect(this).type.toBeAssignableTo<HydratedDocument<IDocument>>();
  expect(res).type.not.toBeAssignableTo<Query<any, any>>();
});

schema.pre('save', { document: false, query: true }, function() {
  expect(this).type.toBe<never>();
});

schema.post('save', { document: false, query: true }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre('save', { document: false, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post('save', { document: false, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre('init', function() {
  expect(this).type.toBeAssignableTo<HydratedDocument<IDocument>>();
});

schema.pre('estimatedDocumentCount', function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('estimatedDocumentCount', function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('estimatedDocumentCount', { document: false, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('estimatedDocumentCount', { document: false, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('estimatedDocumentCount', { document: true, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('estimatedDocumentCount', { document: true, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('estimatedDocumentCount', { document: true, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post('estimatedDocumentCount', { document: true, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre('estimatedDocumentCount', { document: false, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post('estimatedDocumentCount', { document: false, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre('countDocuments', function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('countDocuments', function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('countDocuments', { document: false, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('countDocuments', { document: false, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('countDocuments', { document: true, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('countDocuments', { document: true, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('countDocuments', { document: true, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post('countDocuments', { document: true, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre('countDocuments', { document: false, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post('countDocuments', { document: false, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre('deleteMany', function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('deleteMany', function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('deleteMany', { document: false, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('deleteMany', { document: false, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('deleteMany', { document: true, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('deleteMany', { document: true, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('deleteMany', { document: true, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post('deleteMany', { document: true, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre('deleteMany', { document: false, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post('deleteMany', { document: false, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre('distinct', function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('distinct', function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('distinct', { document: false, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('distinct', { document: false, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('distinct', { document: true, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('distinct', { document: true, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('distinct', { document: true, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post('distinct', { document: true, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre('distinct', { document: false, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post('distinct', { document: false, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre('find', function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('find', function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('find', { document: false, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('find', { document: false, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('find', { document: true, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('find', { document: true, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('find', { document: true, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post('find', { document: true, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre('find', { document: false, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post('find', { document: false, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre('findOne', function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('findOne', function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('findOne', { document: false, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('findOne', { document: false, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('findOne', { document: true, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('findOne', { document: true, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('findOne', { document: true, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post('findOne', { document: true, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre('findOne', { document: false, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post('findOne', { document: false, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre('findOneAndDelete', function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('findOneAndDelete', function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('findOneAndDelete', { document: false, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('findOneAndDelete', { document: false, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('findOneAndDelete', { document: true, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('findOneAndDelete', { document: true, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('findOneAndDelete', { document: true, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post('findOneAndDelete', { document: true, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre('findOneAndDelete', { document: false, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post('findOneAndDelete', { document: false, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre('findOneAndReplace', function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('findOneAndReplace', function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('findOneAndReplace', { document: false, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('findOneAndReplace', { document: false, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('findOneAndReplace', { document: true, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('findOneAndReplace', { document: true, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('findOneAndReplace', { document: true, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post('findOneAndReplace', { document: true, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre('findOneAndReplace', { document: false, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post('findOneAndReplace', { document: false, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre('findOneAndUpdate', function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('findOneAndUpdate', function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('findOneAndUpdate', { document: false, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('findOneAndUpdate', { document: false, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('findOneAndUpdate', { document: true, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('findOneAndUpdate', { document: true, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('findOneAndUpdate', { document: true, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post('findOneAndUpdate', { document: true, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre('findOneAndUpdate', { document: false, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post('findOneAndUpdate', { document: false, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre('replaceOne', function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('replaceOne', function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('replaceOne', { document: false, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('replaceOne', { document: false, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('replaceOne', { document: true, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('replaceOne', { document: true, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('replaceOne', { document: true, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post('replaceOne', { document: true, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre('replaceOne', { document: false, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post('replaceOne', { document: false, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre('updateMany', function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('updateMany', function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('updateMany', { document: false, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('updateMany', { document: false, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('updateMany', { document: true, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('updateMany', { document: true, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('updateMany', { document: true, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post('updateMany', { document: true, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre('updateMany', { document: false, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post('updateMany', { document: false, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre('updateOne', function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('updateOne', function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('updateOne', { document: false, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('updateOne', { document: false, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('updateOne', { document: true, query: false }, function() {
  expect(this).type.toBeAssignableTo<HydratedDocument<IDocument>>();
});

schema.post('updateOne', { document: true, query: false }, function(res) {
  expect(this).type.toBeAssignableTo<HydratedDocument<IDocument>>();
  expect(res).type.toBeAssignableTo<HydratedDocument<IDocument>>();
});

schema.pre('updateOne', { document: true, query: true }, function() {
  expect(this).type.toBeAssignableTo<Query<any, any> | HydratedDocument<IDocument>>();
});

schema.post('updateOne', { document: true, query: true }, function(res) {
  expect(this).type.toBeAssignableTo<Query<any, any> | HydratedDocument<IDocument>>();
  expect(res).type.toBe<any>();
});

schema.pre('updateOne', { document: false, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post('updateOne', { document: false, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre('deleteOne', function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('deleteOne', function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('deleteOne', { document: false, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post('deleteOne', { document: false, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre('deleteOne', { document: true, query: false }, function() {
  expect(this).type.toBeAssignableTo<HydratedDocument<IDocument>>();
});

schema.post('deleteOne', { document: true, query: false }, function(res) {
  expect(this).type.toBeAssignableTo<HydratedDocument<IDocument>>();
  expect(res).type.toBeAssignableTo<HydratedDocument<IDocument>>();
});

schema.pre('deleteOne', { document: true, query: true }, function() {
  expect(this).type.toBeAssignableTo<Query<any, any> | HydratedDocument<IDocument>>();
});

schema.post('deleteOne', { document: true, query: true }, function(res) {
  expect(this).type.toBeAssignableTo<Query<any, any> | HydratedDocument<IDocument>>();
  expect(res).type.toBe<any>();
});

schema.pre('deleteOne', { document: false, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post('deleteOne', { document: false, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany'], function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany'], function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany'], { document: false, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany'], { document: false, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany'], { document: true, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany'], { document: true, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany'], { document: true, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany'], { document: true, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany'], { document: false, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany'], { document: false, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne'], function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne'], function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne'], { document: false, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne'], { document: false, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne'], { document: true, query: false }, function() {
  expect(this).type.toBeAssignableTo<HydratedDocument<IDocument>>();
});

schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne'], { document: true, query: false }, function(res) {
  expect(this).type.toBeAssignableTo<HydratedDocument<IDocument>>();
  expect(res).type.toBeAssignableTo<HydratedDocument<IDocument>>();
});

schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne'], { document: true, query: true }, function() {
  expect(this).type.toBeAssignableTo<Query<any, any> | HydratedDocument<IDocument>>();
});

schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne'], { document: true, query: true }, function(res) {
  expect(this).type.toBeAssignableTo<Query<any, any> | HydratedDocument<IDocument>>();
  expect(res).type.toBe<any>();
});

schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne'], { document: false, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne'], { document: false, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne', 'validate'], function() {
  expect(this).type.toBeAssignableTo<Query<any, any> | HydratedDocument<IDocument>>();
});

schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne', 'validate'], function(res) {
  expect(this).type.toBeAssignableTo<Query<any, any> | HydratedDocument<IDocument>>();
  expect(res).type.toBe<any>();
});

schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne', 'validate'], { document: false, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne', 'validate'], { document: false, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne', 'validate'], { document: true, query: false }, function() {
  expect(this).type.toBeAssignableTo<Query<any, any> | HydratedDocument<IDocument>>();
});

schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne', 'validate'], { document: true, query: false }, function(res) {
  expect(this).type.toBeAssignableTo<HydratedDocument<IDocument>>();
  expect(res).type.toBeAssignableTo<HydratedDocument<IDocument>>();
});

schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne', 'validate'], { document: true, query: true }, function() {
  expect(this).type.toBeAssignableTo<Query<any, any> | HydratedDocument<IDocument>>();
});

schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne', 'validate'], { document: true, query: true }, function(res) {
  expect(this).type.toBeAssignableTo<Query<any, any> | HydratedDocument<IDocument>>();
  expect(res).type.toBe<any>();
});

schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne', 'validate'], { document: false, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne', 'validate'], { document: false, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'save', 'updateOne', 'deleteOne', 'validate'], function() {
  expect(this).type.toBeAssignableTo<Query<any, any> | HydratedDocument<IDocument>>();
});

schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'save', 'updateOne', 'deleteOne', 'validate'], function(res) {
  expect(this).type.toBeAssignableTo<Query<any, any> | HydratedDocument<IDocument>>();
  expect(res).type.toBe<any>();
});

schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'save', 'updateOne', 'deleteOne', 'validate'], { document: false, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'save', 'updateOne', 'deleteOne', 'validate'], { document: false, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'save', 'updateOne', 'deleteOne', 'validate'], { document: true, query: false }, function() {
  expect(this).type.toBeAssignableTo<HydratedDocument<IDocument>>();
});

schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'save', 'updateOne', 'deleteOne', 'validate'], { document: true, query: false }, function(res) {
  expect(this).type.toBeAssignableTo<HydratedDocument<IDocument>>();
  expect(res).type.toBeAssignableTo<Query<any, any> | HydratedDocument<IDocument>>();
});

schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'save', 'updateOne', 'deleteOne', 'validate'], { document: true, query: true }, function() {
  expect(this).type.toBeAssignableTo<Query<any, any> | HydratedDocument<IDocument>>();
});

schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'save', 'updateOne', 'deleteOne', 'validate'], { document: true, query: true }, function(res) {
  expect(this).type.toBeAssignableTo<Query<any, any> | HydratedDocument<IDocument>>();
  expect(res).type.toBe<any>();
});

schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'save', 'updateOne', 'deleteOne', 'validate'], { document: false, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'save', 'updateOne', 'deleteOne', 'validate'], { document: false, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

schema.pre(['save', 'updateOne', 'deleteOne', 'validate'], function() {
  expect(this).type.toBeAssignableTo<Query<any, any> | HydratedDocument<IDocument>>();
});

schema.post(['save', 'updateOne', 'deleteOne', 'validate'], function(res) {
  expect(this).type.toBeAssignableTo<Query<any, any> | HydratedDocument<IDocument>>();
  expect(res).type.toBe<any>();
});

schema.pre(['save', 'updateOne', 'deleteOne', 'validate'], { document: false, query: true }, function() {
  expect(this).type.toBe<Query<any, any>>();
});

schema.post(['save', 'updateOne', 'deleteOne', 'validate'], { document: false, query: true }, function(res) {
  expect(this).type.toBe<Query<any, any>>();
  expect(res).type.toBe<any>();
});

schema.pre(['save', 'updateOne', 'deleteOne', 'validate'], { document: true, query: false }, function() {
  expect(this).type.toBeAssignableTo<HydratedDocument<IDocument>>();
});

schema.post(['save', 'updateOne', 'deleteOne', 'validate'], { document: true, query: false }, function(res) {
  expect(this).type.toBeAssignableTo<HydratedDocument<IDocument>>();
  expect(res).type.toBeAssignableTo<HydratedDocument<IDocument>>();
});

schema.pre(['save', 'updateOne', 'deleteOne', 'validate'], { document: true, query: true }, function() {
  expect(this).type.toBeAssignableTo<Query<any, any> | HydratedDocument<IDocument>>();
});

schema.post(['save', 'updateOne', 'deleteOne', 'validate'], { document: true, query: true }, function(res) {
  expect(this).type.toBeAssignableTo<Query<any, any> | HydratedDocument<IDocument>>();
  expect(res).type.toBe<any>();
});

schema.pre(['save', 'updateOne', 'deleteOne', 'validate'], { document: false, query: false }, function() {
  expect(this).type.toBe<never>();
});

schema.post(['save', 'updateOne', 'deleteOne', 'validate'], { document: false, query: false }, function(res) {
  expect(this).type.toBe<never>();
  expect(res).type.toBe<never>();
});

/* end of generated tests */
